export const testActivityListData = [
  {
    id: '1',
    rowType: 'run',
    sortOrder: 1,
    column1: 1,
    column2: 'search me',
  },
  {
    id: '2',
    rowType: 'run',
    sortOrder: 1,
    column1: 2,
    column2: 'search me',
  },
  {
    id: '3',
    rowType: 'run',
    sortOrder: 1,
    column1: 3,
    column2: 'search me',
  },
  {
    id: '4',
    rowType: 'future',
    sortOrder: 2,
    column1: 1,
    column2: 'search me one',
  },
  {
    id: '5',
    rowType: 'future',
    sortOrder: 2,
    column1: 2,
    column2: 'search me two',
  },
  {
    id: '6',
    rowType: 'future',
    sortOrder: 2,
    column1: 3,
    column2: 'search me three',
  },
  {
    id: '7',
    rowType: 'past',
    sortOrder: 0,
    column1: 1,
    column2: 'search me',
  },
  {
    id: '8',
    rowType: 'past',
    sortOrder: 0,
    column1: 2,
    column2: 'search me',
  },
  {
    id: '9',
    rowType: 'past',
    sortOrder: 0,
    column1: 3,
    column2: 'search me',
  },
];
